const constelacoes = [
    { nome: "Andrômeda", img: "andromeda.png", link: "andromeda.html" },
    { nome: "Antilia", img: "pag.png", link: "pag.html", descricao: "Antilia, a máquina pneumática" },
    { nome: "Apus", img: "apus.png", link: "apus.html", descricao: "Apus, a ave-do-paraíso" },
    { nome: "Aquarius", img: "aquarius.png", link: "aquarius.html", descricao: "Aquarius, aquário, o carregador de água" },
    { nome: "Áquila", img: "aquila.png", link: "aquila.html", descricao: "Áquila, a águia" },
    { nome: "Ara", img: "ara.png", link: "ara.html", descricao: "Ara, o altar" },
    { nome: "Áries", img: "aries.png", link: "aries.html", descricao: "Áries, o carneiro" },
    { nome: "Auriga", img: "auriga.png", link: "auriga.html", descricao: "Auriga, o cocheiro" },
    { nome: "Bootes", img: "bootes.png", link: "bootes.html", descricao: "Bootes, o boieiro" },
    { nome: "Caelum", img: "caelum.png", link: "caelum.html", descricao: "Caelum, o cinzel" },
    { nome: "Camelopardalis", img: "camelopardalis.png", link: "camelopardalis.html", descricao: "Camelopardalis, a girafa" },
    { nome: "Cancer", img: "cancer.png", link: "cancer.html", descricao: "Cancer, o caranguejo" },
    { nome: "Canes Venaciti", img: "canesvenaciti.png", link: "canesvenaciti.html", descricao: "Canes Venaciti, os cães de caça" },
    { nome: "Canis Major", img: "canismajor.png", link: "canismajor.html", descricao: "Canis Major, o cão maior" },
    { nome: "Canis Minor", img: "canisminor.png", link: "canisminor.html", descricao: "Canis Minor, o cão menor" },
    { nome: "Capricornus", img: "capricornus.png", link: "capricornus.html", descricao: "Capricornus, capricórnio, a cabra do mar" },
    { nome: "Carina", img: "carina.png", : "carina.html", descricao: "Carina, a carena (ou quilha) do navio" },
    { nome: "Cassiopeia", img: "cassiopeia.png", link: "cassiopeia.html" },
    { nome: "Centaurus", img: "centaurus.png", link: "centaurus.html", descricao: "Centaurus, o centauro" },
    { nome: "Cepheus", img: "cepheus.png", link: "cepheus.html" },
    { nome: "Cetus", img: "cetus.png", link: "cetus.html", descricao: "Cetus, a baleia" },
    { nome: "Chamaleon", img: "chamaleon.png", link: "chamaleon.html", descricao: "Chamaleon, o camaleão" },
    { nome: "Circinus", img: "circinus.png", link: "circinus.html", descricao: "Circinus, o compasso" },
    { nome: "Columba", img: "columba.png", link: "columba.html", descricao: "Columba, a pomba" },
    { nome: "Coma Berenices", img: "comaberenices.png", link: "comaberenices.html", descricao: "Coma Berenices, a cabeleira de Berenice" },
    { nome: "Corona Australis", img: "coronaaustralis.png", link: "coronaaustralis.html", descricao: "Corona Australis, a coroa austral (ou a coroa do sul)" },
    { nome: "Corona Borealis", img: "coronaborealis.png", link: "coronaborealis.html", descricao: "Corona Borealis, a coroa do norte (ou coroa do norte)" },
    { nome: "Corvus", img: "corvus.png", link: "corvus.html", descricao: "Corvus, o corvo" },
    { nome: "Crater", img: "crater.png", link: "crater.html", descricao: "Crater, a taça" },
    { nome: "Crux", img: "crux.png", link: "crux.html", descricao: "Crux, o cruzeiro do sul" },
    { nome: "Cygnus", img: "cygnus.png", link: "cygnus.html", descricao: "Cygnus, o cisne" },
    { nome: "Delphinus", img: "delphinus.png", link: "delphinus.html", descricao: "Delphinus, o delfim/ o golfinho" },
    { nome: "Dorado", img: "dorado.png", link: "dorado.html", descricao: "Dorado, o peixe-espada" },
    { nome: "Draco", img: "draco.png", link: "draco.html", descricao: "Draco, o dragão" },
    { nome: "Equuleus", img: "equuleus.png", link: "equuleus.html", descricao: "Equuleus, o pequeno cavalo" },
    { nome: "Eridanus", img: "eridanus.png", link: "eridanus.html", descricao: "Eridanus, o rio" },
    { nome: "Fornax", img: "fornax.png", link: "fornax.html", descricao: "Fornax, a fornalha" },
    { nome: "Gemini", img: "gemini.png", link: "gemini.html", descricao: "Gemini, os gêmeos" },
    { nome: "Grus", img: "grus.png", link: "grus.html", descricao: "Grus, o grou" },
    { nome: "Hercules", img: "hercules.png", link: "hercules.html" },
    { nome: "Horologium", img: "horologium.png", link: "horologium.html", descricao: "Horologium, o relógio" },
    { nome: "Hydra", img: "hydra.png", link: "hydra.html", descricao: "Hydra, o monstro marinho" },
    { nome: "Hydrus", img: "hydrus.png", link: "hydrus.html", descricao: "Hydrus, a cobra d’água" },
    { nome: "Indus", img: "indus.png", link: "indus.html", descricao: "Indus, o índio" },
    { nome: "Lacerta", img: "lacerta.png", link: "lacerta.html", descricao: "Lacerta, o lagarto" },
    { nome: "Leo", img: "leo.png", link: "leo.html", descricao: "Leo, o leão" },
    { nome: "Leo Minor", img: "leominor.png", link: "leominor.html", descricao: "Leo Minor, o leão menor" },
    { nome: "Lepus", img: "lepus.png", link: "lepus.html", descricao: "Lepus, a lebre" },
    { nome: "Libra", img: "libra.png", link: "libra.html", descricao: "Libra, a balança" },
    { nome: "Lupus", img: "lupus.png", link: "lupus.html", descricao: "Lupus, o lobo" },
    { nome: "Lynx", img: "lynx.png", link: "lynx.html", descricao: "Lynx, o lince" },
    { nome: "Lyra", img: "lyra.png", link: "lyra.html", descricao: "Lyra, a lira" },
    { nome: "Mensa", img: "mensa.png", link: "mensa.html", descricao: "Mensa, o Monte Mensa na Cidade do Cabo" },
    { nome: "Microscopium", img: "microscopium.png", link: "microscopium.html", descricao: "Microscopium, o microscópio" },
    { nome: "Monoceros", img: "monoceros.png", link: "monoceros.html", descricao: "Monoceros, o unicórnio" },
    { nome: "Musca", img: "musca.png", link: "musca.html", descricao: "Musca, a mosca" },
    { nome: "Norma", img: "norma.png", link: "norma.html", descricao: "Norma, o esquadro" },
    { nome: "Octans", img: "octans.png", link: "octans.html", descricao: "Octans, o oitante" },
    { nome: "Ophiuchus", img: "ophiuchus.png", link: "ophiuchus.html", descricao: "Ophiuchus, o serpentário" },
    { nome: "Orion", img: "orion.png", link: "orion.html", descricao: "Orion, o caçador" },
    { nome: "Pavo", img: "pavo.png", link: "pavo.html", descricao: "Pavo, o pavão" },
    { nome: "Pegasus", img: "pegasus.png", link: "pegasus.html", descricao: "Pegasus, o cavalo alado" },
    { nome: "Perseus", img: "perseus.png", link: "perseus.html" },
    { nome: "Phoenix", img: "phoenix.png", link: "phoenix.html", descricao: "Phoenix, a fênix" },
    { nome: "Pictor", img: "pictor.png", link: "pictor.html", descricao: "Pictor, o pintor" },
    { nome: "Pisces", img: "pisces.png", link: "pisces.html", descricao: "Pisces, os peixes" },
    { nome: "Piscis Austrinis", img: "piscisaustrinis.png", link: "piscisaustrinis.html", descricao: "Piscis Austrinis, o peixe austral (ou peixe do sul)" },
    { nome: "Puppis", img: "puppis.png", link: "puppis.html", descricao: "Puppis, a popa (do navio)" },
    { nome: "Pyxis", img: "pyxis.png", link: "pyxis.html", descricao: "Pyxis, a bússola" },
    { nome: "Reticulum", img: "reticulum.png", link: "reticulum.html", descricao: "Reticulum, o retículo" },
    { nome: "Sagitta", img: "sagitta.png", link: "sagitta.html", descricao: "Sagitta, a flecha" },
    { nome: "Sagittarius", img: "sagittarius.png", link: "sagittarius.html", descricao: "Sagittarius, sagitário, o arqueiro" },
    { nome: "Scorpius", img: "scorpius.png", link: "scorpius.html", descricao: "Scorpius, o escorpião" },
    { nome: "Sculptor", img: "sculptor.png", link: "sculptor.html", descricao: "Sculptor, o escultor" },
    { nome: "Scutum", img: "scutum.png", link: "scutum.html", descricao: "Scutum, o escudo" },
    { nome: "Serpens", img: "serpens.png", link: "serpens.html", descricao: "Serpens, a serpente" },
    { nome: "Sextan", img: "sextan.png", link: "sextan.html", descricao: "Sextan, o sextante" },
    { nome: "Taurus", img: "taurus.png", link: "taurus.html", descricao: "Taurus, o touro" },
    { nome: "Telescopium", img: "telescopium.png", link: "telescopium.html", descricao: "Telescopium, o telescópio" },
    { nome: "Triangulum", img: "triangulum.png", link: "triangulum.html", descricao: "Triangulum, o triângulo" },
    { nome: "Triangulum Australe", img: "triangulumaustrale.png", link: "triangulumaustrale.html", descricao: "Triangulum Australe, o triângulo austral (triângulo do sul)" },
    { nome: "Tucana", img: "tucana.png", link: "tucana.html", descricao: "Tucana, o tucano" },
    { nome: "Ursa Major", img: "ursa-maior.png", link: "ursamajor.html", descricao: "Ursa Major, a ursa maior" },
    { nome: "Ursa Minor", img: "ursa-menor.png", link: "ursaminor.html", descricao: "Ursa Minor, a ursa menor" },
    { nome: "Vela", img: "vela.png", link: "vela.html", descricao: "Vela, a vela (do navio)" },
    { nome: "Virgo", img: "virgo.png", link: "virgo.html", descricao: "Virgo, a virgem" },
    { nome: "Volans", img: "volans.png", link: "volans.html", descricao: "Volans, originalmente Piscis Volans, o peixe-voador" },
    { nome: "Vulpecula", img: "vulpecula.png", link: "vulpecula.html", descricao: "Vulpecula, originalmente Vulpecula cum Ansere, a raposa com o ganso" },
  ];
  
  const container = document.getElementById('constelacoes');
  
  constelacoes.forEach(constelacao => {
    const div = document.createElement('div');
    div.classList.add('constelacao');
    div.innerHTML = `
      <img src="${constelacao.img}" alt="${constelacao.nome} ${constelacao.descricao ? ' - ' + constelacao.descricao : ''}">
      <p>${constelacao.nome}</p>
      <a href="${constelacao.link}" class="link-constelacao">Saiba Mais</a>
    `;
    container.appendChild(div);
  });